apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
  - name: consumer
    image: kafka-consumer:latest  # Değiştirin
    ports:
    - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: NodePort  # Dış erişim için NodePort kullanıyoruz
  selector:
    app: consumer
  ports:
  - name: http
    protocol: TCP
    port: 9093
    targetPort: 9093
