FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY kafka-producer-consumer/kafka-consumer/pom.xml ./

RUN mvn -f kafka-producer-consumer/kafka-consumer/pom.xml clean install

COPY kafka-producer-consumer/kafka-consumer/target/kafka-consumer-*.jar ./

COPY kafka-producer-consumer/kafka-consumer/consumer.java ./

CMD ["java", "-jar", "kafka-consumer-*.jar"]

ENV KAFKA_BROKERS="localhost:9092"

EXPOSE 9092
