FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY pom.xml ./

RUN mvn -f kafka-producer-consumer/kafka-producer/pom.xml clean install

COPY kafka-producer-*.jar .

CMD echo "Hello World"

COPY producer.java .

CMD ["java", "-jar", "kafka-producer-*.jar"]

ENV KAFKA_BROKERS="localhost:9092"

EXPOSE 9092
